# Generated by Django 3.1.3 on 2024-05-08 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ordereddishingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitemingredient',
            name='cart_item',
        ),
        migrations.RemoveField(
            model_name='cartitemingredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart_item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='machine',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='CartItemIngredient',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
