# Generated by Django 3.1.3 on 2024-05-08 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='adding_datetime',
        ),
    ]
