# Generated by Django 3.1.3 on 2024-05-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_cartitem_adding_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_item',
        ),
    ]
