# Generated by Django 3.1.3 on 2024-05-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_order_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number_in_queue',
            field=models.IntegerField(null=True),
        ),
    ]
