# Generated by Django 3.1.3 on 2024-05-08 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_item',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='api.cartitem'),
            preserve_default=False,
        ),
    ]
