# Generated by Django 3.1.3 on 2024-05-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_order_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_item',
        ),
    ]
